modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

issueTrackerURL="https://github.com/banna12345bob/map-drawing/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory

#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

logoFile="assets/map_drawing/textures/item/drawable_map.png" #optional

credits="Constantly & Andromeda-Galaxy29" #optional

authors="Constantly"

description='''
Ever wanted to map your world by hand. Well now you can!
Art by Andromeda-Galaxy29
'''

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
